package club.owefsad.CentralRepository.WebAPI.mapper;

import club.owefsad.CentralRepository.WebAPI.entity.ScanProcess;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ScanProcessMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table scan_process
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table scan_process
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    int insert(ScanProcess record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table scan_process
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    int insertSelective(ScanProcess record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table scan_process
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    ScanProcess selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table scan_process
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    int updateByPrimaryKeySelective(ScanProcess record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table scan_process
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    int updateByPrimaryKey(ScanProcess record);

    int counts();

    int countByState(String state);
}