package club.owefsad.CentralRepository.WebAPI.mapper;

import club.owefsad.CentralRepository.WebAPI.entity.ScanResult;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ScanResultMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table scan_result
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table scan_result
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    int insert(ScanResult record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table scan_result
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    int insertSelective(ScanResult record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table scan_result
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    ScanResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table scan_result
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    int updateByPrimaryKeySelective(ScanResult record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table scan_result
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    int updateByPrimaryKey(ScanResult record);

    List<ScanResult> list(ScanResult record);

    Integer todayRecord();

    Integer totalRecord();

    Integer updateRecordState(ScanResult record);
}