package club.owefsad.CentralRepository.WebAPI.entity;

public class ScanResult {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column scan_result.id
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * scan_result.process_id
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private Integer processId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * scan_result.call_class
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private String callClass;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * scan_result.call_method
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private String callMethod;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * scan_result.target_class
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private String targetClass;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * scan_result.target_method
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private String targetMethod;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column scan_result.state
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * scan_result.create_time
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * scan_result.update_time
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private Long updateTime;

    private ScanProcess process;

    public ScanProcess getProcess() {
        return process;
    }

    public void setProcess(ScanProcess process) {
        this.process = process;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * scan_result.id
     *
     * @return the value of scan_result.id
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column scan_result.id
     *
     * @param id the value for scan_result.id
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * scan_result.process_id
     *
     * @return the value of scan_result.process_id
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public Integer getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * scan_result.process_id
     *
     * @param processId the value for scan_result.process_id
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setProcessId(Integer processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * scan_result.call_class
     *
     * @return the value of scan_result.call_class
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public String getCallClass() {
        return callClass;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * scan_result.call_class
     *
     * @param callClass the value for scan_result.call_class
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setCallClass(String callClass) {
        this.callClass = callClass == null ? null : callClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * scan_result.call_method
     *
     * @return the value of scan_result.call_method
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public String getCallMethod() {
        return callMethod;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * scan_result.call_method
     *
     * @param callMethod the value for scan_result.call_method
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setCallMethod(String callMethod) {
        this.callMethod = callMethod == null ? null : callMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * scan_result.target_class
     *
     * @return the value of scan_result.target_class
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public String getTargetClass() {
        return targetClass;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * scan_result.target_class
     *
     * @param targetClass the value for scan_result.target_class
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setTargetClass(String targetClass) {
        this.targetClass = targetClass == null ? null : targetClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * scan_result.target_method
     *
     * @return the value of scan_result.target_method
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public String getTargetMethod() {
        return targetMethod;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * scan_result.target_method
     *
     * @param targetMethod the value for scan_result.target_method
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setTargetMethod(String targetMethod) {
        this.targetMethod = targetMethod == null ? null : targetMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * scan_result.state
     *
     * @return the value of scan_result.state
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * scan_result.state
     *
     * @param state the value for scan_result.state
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * scan_result.create_time
     *
     * @return the value of scan_result.create_time
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * scan_result.create_time
     *
     * @param createTime the value for scan_result.create_time
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * scan_result.update_time
     *
     * @return the value of scan_result.update_time
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * scan_result.update_time
     *
     * @param updateTime the value for scan_result.update_time
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime / 1000;
    }
}