package club.owefsad.CentralRepository.WebAPI.entity;

public class ScanProcess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_process.id
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_process.package_name
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private String packageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_process.signature
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_process.times
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private Integer times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_process.state
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_process.create_time
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scan_process.update_time
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_process.id
     *
     * @return the value of scan_process.id
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_process.id
     *
     * @param id the value for scan_process.id
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_process.package_name
     *
     * @return the value of scan_process.package_name
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_process.package_name
     *
     * @param packageName the value for scan_process.package_name
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_process.signature
     *
     * @return the value of scan_process.signature
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_process.signature
     *
     * @param signature the value for scan_process.signature
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_process.times
     *
     * @return the value of scan_process.times
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_process.times
     *
     * @param times the value for scan_process.times
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_process.state
     *
     * @return the value of scan_process.state
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_process.state
     *
     * @param state the value for scan_process.state
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_process.create_time
     *
     * @return the value of scan_process.create_time
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_process.create_time
     *
     * @param createTime the value for scan_process.create_time
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scan_process.update_time
     *
     * @return the value of scan_process.update_time
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scan_process.update_time
     *
     * @param updateTime the value for scan_process.update_time
     *
     * @mbg.generated Sun Jan 16 20:00:03 CST 2022
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}